services:
  app:
    image: valentinusdelvin/nutrimama:main
    container_name: daris_be
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:3014:${APPPORT}"
    networks:
      - mariadb_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Asia/Jakarta


networks:
  mariadb_network:
    external: true
