services:
  app:
    build:
      container_name: daris_be
      restart: unless-stopped
      env_file: .env
      dockerfile: Dockerfile
    ports:
      - "3014:{APPPORT}"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    external: true